### ISSUE TITLE
DelegatingConverter and CycleAvoidingMappingContext

### ISSUE THREAD

**Issue by twallmey** [mapstruct/mapstruct-spring-extensions#101]
Hi,

I've defined a Mapper that should avoid cycles. For this reason I've just followed Mapstructs suggestion and invented the CycleAvoidingMappingContext. Doing so my current mapper looks like:

```java
@Mapper(
    config = MapstructConfig.class
)
public interface DataModificationMapperV1Physical extends Converter<DataModificationV1, DataModification> {
  DataModification convert(DataModificationV1 from, @Context CycleAvoidingMappingContext context);

  @InheritInverseConfiguration
  @DelegatingConverter
  DataModificationV1 inverseConvert(DataModification from, @Context CycleAvoidingMappingContext context);
}
```

My problem obviously results from the additionally defined @DelegatingConverter because when compiling I get the following error:
**Can only generate a delegating converter for methods with exactly one parameter and non-void return type.**

Does anyone have an idea how to combine the CycleAvoidingMappingContext with @DelegatingConverter successfully?

Many thanks in advance,

Thorben

**Comment by Chessray** [comment]
In a broader sense, the question is asking about `@DelegatingConverter` with additional `@Context` parameters. You're right, this is a simple omission. I'll include it in the next release.

**Comment by twallmey** [comment]
Great to hear! Do you already have an idea when the next release will be available that contains this feature? 

I'm asking because we are currently working on a bigger innovation project. Does ist make sense to wait oder would you think that it will take a longer time? In this case we would have to look for a workaround.

**Comment by Chessray** [comment]
Sorry, looking at this again I just realised that I have to retract my previous response. Your base `convert` method doesn't conform to [Spring's standard](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/convert/converter/Converter.html#convert(S)), so the `@DelegatingConverter` cannot work in this scenario anyway. If you want to use `Context` objects, you can't have the Mapper extend the `Converter` interface.

**Comment by petitgros** [comment]
Hello,

I am trying to use spring `ConversionService` with a generic custom `Converter` including `CycleAvoidingMappingContext`  like below.

1. If i use `DelegatingConverter` in this custom `Converter` TToSConverter is generated even if there is no `Mapper` annotation.
2. If i use `DelegatingConverter` in subclasses, as described [twallmey](https://github.com/twallmey), it work but only  without using `Context` annotation. Maybe it will by using `BaseMapper` instead `Converter` as interface will generating delegate.

```java
public interface BaseMapper<S, T> extends Converter<S, T> {

    @Nullable
    T convert(@NonNull S source, @Context CycleAvoidingMappingContext context);

    @Nullable
    @Override
    @Named("baseConvert")
    default T convert(@NonNull S source) {
        return convert(source, new CycleAvoidingMappingContext());
    }

    @DelegatingConverter // <--- This generate code below
    @InheritInverseConfiguration
    S invertConvert(T source);
}
```

Unwanted TToSConverter is generated 
```java
@Component
public class TToSConverter implements Converter<T, S> {
  private BaseMapper delegateMapper;

  public TToSConverter(@Autowired final BaseMapper delegateMapper) {
    this.delegateMapper = delegateMapper;
  }

  @Override
  public S convert(final T source) {
    return delegateMapper.invertConvert(source);
  }
}
```
