### ISSUE TITLE
"noconfig" example is not working

### ISSUE THREAD

**Issue by marcotama** [mapstruct/mapstruct-spring-extensions#106]
Hello, thanks for making this extension, it seems a useful addition!

I am having troubles getting it to work, though.
I was following your "noconfig" example but wasn't able to continue due to an import statement not satisfied.
I tried cloning this repository to get to the bottom of this, but things still don't work.

Basically, the class `org.mapstruct.extensions.spring.converter.ConversionServiceAdapter` does not seem to exist.

Can you please advise?

This is a screenshot of the error.
![image](https://github.com/mapstruct/mapstruct-spring-extensions/assets/1052500/de162e69-6948-4b14-80de-cc4318c87c28)

**Comment by Chessray** [comment]
That's the point of this extension. The class will be generated on the compile step during the build process.
