### ISSUE TITLE
ConversionService beans conflict in @WebMvcTest annotated tests with Spring Cloud 2023.0.1

### ISSUE THREAD

**Issue by emili4ciccone** [mapstruct/mapstruct-spring-extensions#107]
So, I am trying to write Junit tests for my web application; in order to do so, I have written a `@Configuration` class using the `@ConverterScan` annotation, in order to collect and initialize all of my Converter methods into ConversionService: 

```
@Configuration
@ComponentScan("org.mapstruct.extensions.spring")
@ComponentScan("myproject.common.mapper")
@ConverterScan(basePackageClasses = MapperSpringConfig.class)
@Import({SecurityTestConfiguration.class, SimpleMeterRegistry.class})
public class ControllerTestConfiguration {

}
```

(Class SecurityTestConfiguration only instantiate a bean for SecurityFilterChain, while package **myproject.common.mapper** contains all of my Converter-extending mappers.)

I integrate this configuration in my Controller tests, written with `@WebMvcTest` annotation, like this: 

```
@WebMvcTest
@ContextConfiguration(classes = { ControllerTestConfiguration.class, MyController.class })
class MyControllerTest {

    private MockMvc mockMvc;

    @Autowired
    private WebApplicationContext webApplicationContext;
    @Autowired
    private MyController myController;
    @MockBean
    private myService myServiceMock;

    @BeforeEach
    void init() {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext).build();
    }
    
    [...]

}
```

Class MyController looks like this: 

```
@RestController
@RequestMapping(MyController.MY_URL)
@CrossOrigin
@Slf4j
public class MyController {

    public static final String MY_URL = "/data";

    private final MyService dataCenterService;
    private final ConversionService conversionService;

    @Autowired
    public MyController(MyService myService, ConversionService conversionService) {
        this.myService = myService;
        this.conversionService = conversionService;
    }
    
    @GetMapping
    [..]

}
```

When the application is based on Spring Cloud **2022.0.5**, my tests run fine. FYI, at this point my `@WebMvcTest` is included in package **spring-boot-test-autoconfigure:3.0.13**. 
Unfortunately, I am also migrating this application to **Spring Cloud 2023.0.1** and Java 21. When I migrate, change all of my spring-boot-* dependencies to version **3.2.4** and I try to run these same tests, for the Controller tests only I get this error:

**`Error creating bean with name 'myController': Unsatisfied dependency expressed through constructor parameter 1: No qualifying bean of type 'org.springframework.core.convert.ConversionService' available: expected single matching bean but found 2: basicConversionService,mvcConversionService`** 

It seems like the framework is unable to merge my generated ConversionService and the mvcConversionService instantiated by `@WebMvcTest` annotation, but only for Spring Cloud 2023.0.1, since it worked fine with Spring Cloud 2022.0.5. 

**Am I missing some configuration?** I only have these problems **during my unit tests**, everything else works fine when I run the application with Spring Cloud 2023.0.1. 

I have added the following dependencies in my pom.xml: 

```
        <dependency>
            <groupId>org.mapstruct.extensions.spring</groupId>
            <artifactId>mapstruct-spring-extensions</artifactId>
            <version>1.1.1</version>
        </dependency>

        <dependency>
            <groupId>org.mapstruct.extensions.spring</groupId>
            <artifactId>mapstruct-spring-test-extensions</artifactId>
            <scope>test</scope>
            <version>1.1.1</version>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>1.4.2.Final</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.mapstruct.extensions.spring</groupId>
            <artifactId>mapstruct-spring-annotations</artifactId>
            <version>1.1.1</version>
        </dependency>

[...]
             <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                  <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.5.5.Final</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct.extensions.spring</groupId>
                            <artifactId>mapstruct-spring-extensions</artifactId>
                            <version>1.1.1</version>
                        </path>
                    </annotationProcessorPaths>
                  </configuration>
                 </plugin>

```

Also, I would like to avoid to mock all of my Converters, but I would like to use the real thing in order to make my tests more complete (but, at the moment, the only way to make my `@WebMvcTest` annotated tests work is by adding 

```
@MockBean
private MyMapper myMapper 
```

in each test. For completeness, MyMapper is something like

```
@Mapper(config = MapperSpringConfig.class)
public interface MyDTOToBeanMapper extends Converter<MyDTO, MyBean> {

    @Override
    MyBean convert(@Nullable MyDTO source);
}
```

and MapperSpringConfig.class is identical to the example reported in the documentation). 

Thanks in advance!

**Comment by emili4ciccone** [comment]
Hi @Chessray, thank you for you answer!
Again, I don't know whether I am missing something, but I modified my MapperSpringConfig class to: 

```
@MapperConfig(componentModel = "spring", uses = ConversionServiceAdapter.class)
@SpringMapperConfig(generateConverterScan = true, conversionServiceAdapterPackage = "org.mapstruct.extensions.spring.converter")
public interface MapperSpringConfig {

}
```
and I still have the same issue. I also could not find this generated _@ConverterScan_ annotation anywhere, the only _@ConverterScan_ annotation I cound find was the usual one inside `org.mapstruct.extensions.spring.test` package.

If it's useful, when I run my tests a new folder `target/generated-test-sources/test-annotations` is generated, but it is empty.

**Comment by Chessray** [comment]
Sorry, https://mapstruct.org/documentation/spring-extensions/reference/html/#generateConverterScan is probably not clear enough this. In order to activate this generator, you will also have to set the `conversionServiceBeanName` property. In your case, the value should be `"mvcConversionService"`. If that doesn't help, could you please share your project?

**Comment by emili4ciccone** [comment]
Hi again! I followed your advice, and now I have a different issue... Using the generated @ConverterScan annotation my Controller tests run fine, but all my Service tests fail to run with the error:

**`Error creating bean with name 'org.mapstruct.extensions.spring.converter.ConverterRegistrationConfiguration': Unsatisfied dependency expressed through constructor parameter 0: No qualifying bean of type 'org.springframework.core.convert.support.ConfigurableConversionService' available: expected at least 1 bean which qualifies as autowire candidate.`**

I uploaded a [gitHub mock project](https://github.com/emili4ciccone/mapstruct-test) to replicate the problem. I have also tried any combination of use of the @ConverterScan generated and built-in annotation, but nothing seems to work. 
Many thanks!

**Comment by Chessray** [comment]
Hi, sorry I didn't get a chance to look at this earlier.

Please note the second bullet point in the [documentation](https://mapstruct.org/documentation/spring-extensions/reference/html/#generateConverterScan):

> In a test, the developer will still have to provide a `ConfigurableConversionService` themselves.

Please check the example in the documentation. You'll have to follow that pattern for all `SpringBootTest`s that rely on the `ConversionService`.

This happens, because this form of the annotation is intended for production use where we typically _don't_ initialise the `ConversionService` ourselves. Therefore you have to do it yourself in your tests.

**Comment by emili4ciccone** [comment]
Hello, no problem! I modified the project according to the example in the documentation, and I have another error... It may be some kind of conflict between the MVC and the "basic" conversionService? Because if I use the generated Annotation the Controller tests work fine, but the Service tests don't run and return the error:
`Annotation-specified bean name 'converterRegistrationConfiguration' for bean class [org.mapstruct.extensions.spring.test.ConverterRegistrationConfiguration] conflicts with existing, non-compatible bean definition of same name and class [org.mapstruct.extensions.spring.converter.ConverterRegistrationConfiguration] `.

Still, thank you for your support!

**Comment by Chessray** [comment]
Ah, that error makes sense. I hadn't come across this before, but it's basically telling you that having the builtin _and_ the generated annotations in the same project is impossible. They're mutually exclusive. (At least for the moment. There's no particular reason for it, there just was no point in having both in the same project until now.)

**Comment by emili4ciccone** [comment]
Oh, okay! Thank you 😄 I think I can close this issue then. I will keep on following the project to see whether the use of both the builtin and the generated annotations will be implemented... Still, many thanks!
