### ISSUE TITLE
@DecoratedWith is not work with mapstruct-spring-extensions

### ISSUE THREAD

**Issue by Cloud-Lego** [mapstruct/mapstruct-spring-extensions#116]
I try to user mapstruct-spring-extensions to optimize my mapper,but find @DecoratedWith(xxxDecorator.class) is not work when user ConversionService.conver(object,xxx.class)，this is a bug or I use is wrong way?

**Comment by Chessray** [comment]
Could you please provide an example project of what you're asking? What do you mean when you say the annotation doesn't work?

Generally speaking, some of MapStruct's advanced features such as `@DecoratdWith` clash with Spring's `ConversionService`. There are definitely cases where you want to avoid following the `Converter` pattern. This might be one.

**Comment by Cloud-Lego** [comment]
just see the attachment，this is a spring boot applicaiton, UserMapper is declared as a converter with @DecoratdWith class,when I use ConversionService to mapping,this class is not work.
 
 



在 2024-10-02 23:53:07，"Raimund Klein" ***@***.***> 写道：

Could you please provide an example project of what you're asking? What do you mean when you say the annotation doesn't work?

Generally speaking, some of MapStruct's advanced features such as @DecoratdWith clash with Spring's ConversionService. There are definitely cases where you want to avoid following the Converter pattern. This might be one.

**Comment by Chessray** [comment]
> just see the attachment，this is a spring boot applicaiton, UserMapper is declared as a converter with @DecoratdWith class,when I use ConversionService to mapping,this class is not work. 

Sorry, there's no attachment.

**Comment by Cloud-Lego** [comment]
send code zip again, if not receive, try to use this link  demo1







在 2024-10-03 23:17:47，"Raimund Klein" ***@***.***> 写道：

just see the attachment，this is a spring boot applicaiton, UserMapper is declared as a converter with @DecoratdWith class,when I use ConversionService to mapping,this class is not work.

Sorry, there's no attachment.

**Comment by Chessray** [comment]
Sorry, it looks like GitHub removes everything such as links and attachments from your emails. Could you please respond in the issue thread?

**Comment by Cloud-Lego** [comment]
[demo1.zip](https://github.com/user-attachments/files/17247277/demo1.zip)
![image](https://github.com/user-attachments/assets/0c7b80ca-6ce1-4968-979b-01dbde4635ae)
![image](https://github.com/user-attachments/assets/6025fe95-35c6-497f-b4bd-5ba7c3caebb6)

**Comment by Cloud-Lego** [comment]
> Sorry, it looks like GitHub removes everything such as links and attachments from your emails. Could you please respond in the issue thread?
https://github.com/mapstruct/mapstruct-spring-extensions/issues#issuecomment-2391846632

this is the demo
https://github.com/user-attachments/files/17247277/demo1.zip

**Comment by kay73** [comment]
Same here. Seems Spring ConverterService is the root of the problem. Under the hood, it appears to collect every Converter<S,T> bean it finds and puts it in a list that is associated with conversion type pair and does not order them properly.

From the looks of it, Mapstruct does things right: The decorator class is generated, class name ends in "Impl" (no underscore) and has the @Primary annotation alongside @Component and inherits the decorator. The delegate class has @Component and @Qualifier("delegate") and ends in "Impl_". Bean instanciation and injection also seems to function correctly.

When I examine the ConversionService, I find *both* beans in the list of converters for that particular conversion pair with the "delegate" at position 0 and the decorator at position 1.

**Comment by Cloud-Lego** [comment]
I try to solve this in this way
define ConverterService  to replace default
![image](https://github.com/user-attachments/assets/3ab8f3cd-ad69-4eba-8127-2389592f9936)

then ConverterService  will use decorator method

**Comment by Chessray** [comment]
Thanks for the clarification. So we come back to my original assessment:

> Generally speaking, some of MapStruct's advanced features such as `@DecoratedWith` clash with Spring's `ConversionService`. There are definitely cases where you want to avoid following the `Converter` pattern.

I've had advanced cases in various projects where I had to fall back to MapStruct without the Spring extension. It's fully functional; you just have to inject the Mapper directly instead of the `ConversionService`.
