### ISSUE TITLE
Create ability to specify conversion service bean name

### ISSUE THREAD

**Issue by dmham86** [mapstruct/mapstruct-spring-extensions#15]
When an application has multiple conversion service beans, there needs to be a way to specify the name of the ConversionService bean.

**Comment by dmham86** [comment]
@Chessray do you have any plans to release 0.0.2 or an RC soon?

**Comment by Chessray** [comment]
@dmham86 It's out now. Sorry it took so long: https://mapstruct.org/news/2021-02-15-mapstruct-spring-extensions-0-0-2-released/
