### ISSUE TITLE
value in @Generated annotation incorrect when using conversionServiceAdapterClassName

### ISSUE THREAD

**Issue by woodforda** [mapstruct/mapstruct-spring-extensions#19]
Hi,

Minor issue...

When I define my Conversion Service to be  a different name the @Generated annotation has the default value.

```java
@SpringMapperConfig(conversionServiceAdapterClassName ="AvaloqApiMapper")
public @interface AvaloqApiMapperConfig { }
```

and the generated is
```java
@Generated(
    value = "org.mapstruct.extensions.spring.converter.ConversionServiceAdapterGenerator",
    date = "2021-02-24T11:03:43.603282300Z"
)
@Component
public class AvaloqApiMapper {
...
}
```

cheers,
Andrew

**Comment by Chessray** [comment]
This is correct behavior - the `@Generated` annotation contains the name of [the class that generated the output](https://docs.oracle.com/javase/7/docs/api/javax/annotation/Generated.html#value()). `conversionServiceAdapterClassName` determines the name of the _actual_ generated class

**Comment by woodforda** [comment]
ok. apologies.  should have spotted that myself.
