### ISSUE TITLE
Implicit cyclical dependency

### ISSUE THREAD

**Issue by PRIESt512** [mapstruct/mapstruct-spring-extensions#21]
Hi, I started using your development in my application. Faced the following problem.

If the generated mapper uses 'ConversionServiceAdapter' as a dependency then spring not add the mapper to the ConversionService. There is an implicit circular dependency between mapper and 'ConversionServiceAdapter' due to ConversionService. It prevents all converters from being added to the ConversionService. 

For example, the generated class might be like this:

`@Component
public class TestConverter implements Converter<S, T> {

    private ConversionServiceAdapter serviceAdapter;

    public TestConverter(@Lazy ConversionServiceAdapter serviceAdapter) {
        this.serviceAdapter = serviceAdapter;
    }

    @Override
    public T convert(S source) {
        return T;
    }
}`

All mappers are created without race for ConversionServiceAdapter, all mappers are added to ConversionService. Otherwise, the mapper that is using the ConversionServiceAdapter will not be added as a converter. 
ConverterNotFoundException will be thrown.

Applicable for version 0.0.2.

P.S. If I can help, I can do a PR. I would like to get a fix faster

**Comment by Chessray** [comment]
Thank you. That's an interesting one. I noticed a weirdness myself, but hadn't gotten down to the bottom.

This means we might have to influence the format of the generated Mappers rather than only the adapter, so we'll require some assistance from the Mapstruct core. Tagging @filiphr and @sjaakd for visibility.

**Comment by PRIESt512** [comment]
@Lazy I added it to the code generation, I just hadn't tested it yet and was not sure about the beauty of the solution, but how quick a hack could do. However, if you also suggest such an option, then I will check the solution. Yes, I'll make an example that demonstrates this problem.

**Comment by PRIESt512** [comment]
An example of a project with an error is [here](https://github.com/PRIESt512/mapper_failure.git)

А little later I will check the lazy generation)

**Comment by filiphr** [comment]
If you don't use constructor injection then this will work fine. 

There are 2 other options that the Spring Extensions can do:

* Implement a `ModelElementProcessor` that will be executed just after the `ModelElementProcessor` and will look into the constructor and add the `@Lazy` to the appropriate field. This shouldn't be too hard by going through the `Mapper#getConstructor` and checking for `AnnotatedConstructor`, then going through the `AnnotationMapperReference` with a `ListIterator` and replacing the reference by calling `AnnotationMapperReference#withNewAnnotations`.
* Another approach would be to have the concept of `XXXAware` and similar like before with a `ModelElementProcessor` add adding an implementation of the `XXXAware` method.

Honestly, I personally am not a fan of the `@Lazy` annotation as sometimes it might lead to some inconsistencies. However, for this particular case, most likely it is OK.

**Comment by PRIESt512** [comment]
In the end, the reason for this strange behavior turned out to be spring. An _BeanCurrentlyInCreationException_ was actually thrown inside it. But it was suppressed 🤦  This is due to a feature of the DefaultListableBeanFactory implementation. A piece of code for this ill-fated place: 
```

			try {
				Object beanInstance = getBean(beanName);
				if (!(beanInstance instanceof NullBean)) {
					result.put(beanName, (T) beanInstance);
				}
			}
			catch (BeanCreationException ex) {
				Throwable rootCause = ex.getMostSpecificCause();
				if (rootCause instanceof BeanCurrentlyInCreationException) {
					BeanCreationException bce = (BeanCreationException) rootCause;
					String exBeanName = bce.getBeanName();
					if (exBeanName != null && isCurrentlyInCreation(exBeanName)) {
						if (logger.isTraceEnabled()) {
							logger.trace("Ignoring match to currently created bean '" + exBeanName + "': " +
									ex.getMessage());
						}
						onSuppressedException(ex);
						// Ignore: indicates a circular reference when autowiring constructors.
						// We want to find matches other than the currently created bean itself.
						continue;
					}
				}
				throw ex;
			}
```

In fact, this is a clear cyclical dependence that has been rudely suppressed. I'm sitting here and thinking if this is a bug or a feature 🤪

**Comment by danielshiplett** [comment]
I believe that the correct solution, according to the Spring documentation is to add a setter that is marked @Autowired.  This will allow the constructor call to proceed without the cyclical dependency.  Then, once the ConversionServiceAdapter is initialized, Spring will come back and call the Autowired setter.

So in short, remove the generation of the Autowired private field (leave the field, remove the Autowired).  Then add:

```
@Autowired
public void setConversionServiceAdapter(ConversionServiceAdapter conversionServiceAdapter) {
  this.conversionServiceAdapter = conversionServiceAdapter;
}
```

This avoids the need for @Lazy which can cause applications to start successfully even when a required Bean is missing.

**Comment by woodforda** [comment]
I had some issues with Converters not being found due to start up order.   worked around this by setting the @AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE + 50) of where my converters are defined (or component scanned).  This makes them available before the Boot tries to pick them up for the ConversionService.  Obviously, if the converter depends on other beans then this would force earlier instantiation of them too so it's not always viable.

Also inject an ObjectProvider<ConversionServiceAdapter> which I can use to lazily retrieve the service (and still keep constructor injection) when (if) the situation requires.

**Comment by Chessray** [comment]
> I believe that the correct solution, according to the Spring documentation is to add a setter that is marked @Autowired. This will allow the constructor call to proceed without the cyclical dependency. Then, once the ConversionServiceAdapter is initialized, Spring will come back and call the Autowired setter.
> 
> So in short, remove the generation of the Autowired private field (leave the field, remove the Autowired). Then add:
> 
> ```
> @Autowired
> public void setConversionServiceAdapter(ConversionServiceAdapter conversionServiceAdapter) {
>   this.conversionServiceAdapter = conversionServiceAdapter;
> }
> ```
> 
> This avoids the need for @lazy which can cause applications to start successfully even when a required Bean is missing. In this case the lazy will probably be OK as this is all generated code and nothing _should_ be missing.

I agree that the `@Autowired` setter feels somewhat cleaner than `@Lazy`. However, this is in the Mapper itself. At this point, I'm a bit reluctant to modify the mapper generation from the extension. We'll probably go ahead with `@Lazy` if we can include the test example. I'm hoping to find a little time for this over the next couple of days.

**Comment by danielshiplett** [comment]
Yeah.  After I posted by message, I dug into the code and realized that it was core MapStruct and not the extension that would need the change.  Oh well.  I took the proposed MR and tested it and it worked fine.  So I'm OK with the @Lazy annotation being added.
