### ISSUE TITLE
No converter found capable of converting from type

### ISSUE THREAD

**Issue by MicyToy** [mapstruct/mapstruct-spring-extensions#22]
I have introed `mapstruct-spring-extensions`  and config as the docs told.
mapstruct version is `1.4.2.Final`
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct.extensions.spring</groupId>
                            <artifactId>mapstruct-spring-extensions</artifactId>
                            <version>${org.mapstruct.extensions.spring.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
```

and SpringMapperConfig
```
@MapperConfig(componentModel = "spring", uses = ConversionServiceAdapter.class)
@SpringMapperConfig(conversionServiceAdapterPackage = "com.example.converter")
public interface MapStructSpringConfig {
}
```
converter interface (for some reason, changed type name and field name)
```
@Mapper(uses = ConversionServiceAdapter.class)
    interface CarStructMapper extends Converter<Car, CarDTO> {
        @Mappings({
                @Mapping(target = "seatCount", source = "seat.total"),
                @Mapping(target = "product", source = "model"),
        })
        CarDTO convert(Car source);
    }
```

used converter adapter in my class as bellow:
```

    @Autowired
    private ConversionServiceAdapter conversionServiceAdapter;

    // source is an instance of Car
    conversionServiceAdapter.mapCarToCarDTO(source)
```

but I got an exception
```
No converter found capable of converting from type [com.example.Car] to type [com.example.CarDTO]
```

What should I do to fix it. Thanks

**Comment by Chessray** [comment]
The idea is not to inject the generated adapter, but rather the `ConversionService`: https://mapstruct.org/documentation/spring-extensions/reference/html/#mapperAsConverter. Also, this is probably the same issue as #21 .

**Comment by MicyToy** [comment]
`ConversionService` also has this issue.

I fix it by configuring autowired in Spring config.
```
  @Autowired
    public void addFormatters(FormatterRegistry registry) {
        registry.addConverter(new CarMapperImpl());
    }
```

After doing like this, Spring can find mapping implementation.

**Comment by marvk** [comment]
We're trying to integrate `mapstruct-spring-extensions` into our project because it looked very promising. However, the solution suggested by @MicyToy isn't really satisfying in my opinion. I would expect the generated mappers to be added to, or else detected by, `ConversionService` automatically. Is this a configuration issue or are we really expected to register mappers by hand (for now)?

**Comment by Chessray** [comment]
@marvk Please do not hijack this closed thread. Yes, the Mappers will be added to the ConversionService automatically in most cases. However, depending on your SpringBoot setup, this service might not be initialized in a standard fashion. The SpringBoot example project [demonstrates](https://github.com/mapstruct/mapstruct-spring-extensions/blob/main/examples/simple-springboot/src/main/java/org/mapstruct/extensions/spring/example/boot/config/ConverterConfig.java) one way to solve this in case e.g. `spring-boot-starter-web` isn't there.

**Comment by marvk** [comment]
@Chessray Sorry, I didn't want to open what I thought would be a duplicate. I'll have a look and if I can't get it to work, I'll open a new ticket. Cheers!
