### ISSUE TITLE
mapstruct-spring-plus

### ISSUE THREAD

**Issue by ZhaoRd** [mapstruct/mapstruct-spring-extensions#24]
I created a project named `mapstruct-spring-plus` to simplify the use of mapstruct. In this project, `@AutoMap` and `@AutoMapField` annotations are used to automatically generate Mapper interface files. If I want to merge the code into `mapstruct.org`,what should I do? Project address: https://github.com/ZhaoRd/mapstruct-spring-plus.
Use code
```java
@Data
@AutoMap(targetType = Car.class)
public class CarDto {
    private String make;

    @AutoMapField(target = "carType")
    private String type;

}

@Data
public class Car {
    private String make;
    private String carType;
}


@ExtendWith(SpringExtension.class)
@ContextConfiguration(
        classes = {AutoMapTests.AutoMapTestConfiguration.class})
public class AutoMapTests {

    @Autowired
    private IObjectMapper mapper;

    @Test
    public void testDtoToEntity() {

        var dto = new CarDto();
        dto.setMake("M1");
        dto.setType("OTHER");

        Car entity = mapper.map(dto, Car.class);

        assertThat(entity).isNotNull();
        assertThat(entity.getMake()).isEqualTo("M1");
        assertThat(entity.getCarType()).isEqualTo("OTHER");

    }


    @ComponentScan("io.github.zhaord.mapstruct.plus")
    @Configuration
    @Component
    static class AutoMapTestConfiguration {


    }


}
```

**Comment by Chessray** [comment]
Hello,

Thank you for this idea. This looks like something we can incorporate into this extension rather than MapStruct itself. Would you mind preparing a PR into this repo?

**Comment by ZhaoRd** [comment]
@Chessray   ok!

**Comment by filiphr** [comment]
I had a brief look at this and it looks interesting.

I think that there are 2 independent things here:

* The `@AutoMap` which is not Spring dependant and can create standalone Mappers 
* The spring bits

To be honest I think that the `@AutoMap` feature can be achieved entirely without a dependency on a third party library. From what I say you are now forcing users to have a runtime dependency on the mapstruct-plus because of the `AutoMapper`. I don't think that this is entirely needed. Users in theory can define their own base interface and package where they want their mappers to reside.

**Comment by ZhaoRd** [comment]
Yes, @AutoMap  can be achieved entirely without a dependency on a third party library in mapstruct-plus-core module，in especial spring.
If  with not spring, I have no idea for use IObjectMapper interface.
@AutoMap is to use APT to generate the @Mapper interface of mapstruct.  The difference between @AutoMap and @Mapper is that @AutoMap acts on the bean of dto or entity, and @Mapper acts on the user-defined interface.
With @AutoMap, user only dependency IObjectMapper can complete  map bean.
If user want extend map interface，user can extends BaseAutoMapper<S,T> inteface, or  like mapstruct ，use @Mapper to write inteface, and @AutoMap(use=...) .
In spring projects, it is recommended to rely on the boot starter module

**Comment by ZhaoRd** [comment]
@Chessray 
@filiphr 

I create a PR ， this RP implement @AutoMap, please check it. thks;
