### ISSUE TITLE
Utilize standard Spring conversions

### ISSUE THREAD

**Issue by Chessray** [mapstruct/mapstruct-spring-extensions#29]
Spring provides a rich set of standard converters that go beyond MapStruct's built-in functionalities (e.g. UUID to String). It would be beneficial if we could utilize these in order to reduce the burden on the MapStruct user who has to reimplement these in every project.

**Comment by filiphr** [comment]
Just FYI, starting from 1.5 MapStruct will have out of the box support for mapping between String and UUID. See https://github.com/mapstruct/mapstruct/issues/2391.

**Comment by Chessray** [comment]
OK, so maybe not UUID then. 😄 It was only an example. Essentially I'm thinking about a mechanism that will allow the inclusion of the built-in conversions or even those defined in other modules.
