### ISSUE TITLE
"No converter found capable of converting from type" in Spring Boot Starter Web project

### ISSUE THREAD

**Issue by marvk** [mapstruct/mapstruct-spring-extensions#40]
Related to #22 

We're trying to integrate mapstruct-spring-extensions into a project and hit a little bit of a roadblock.

I was under the impression that, when defining a mapper, extending `Converter` and adding a `@Mapper` annotation would be enough for `ConversionService` to pick this mapper up automatically. However, this isn't happening in my Spring Boot project with Spring Boot Starter Web.

This is how I defined a Mapper:

```Kotlin
@Mapper
interface FooMapper : Converter<Foo, FooDto> {
    override fun convert(source: Foo): FooDto
}
```

I've built an [MCVE](https://github.com/marvk/spring-mapstruct-extensions-test) so that you can verify my test setup.

`FooMapperImpl` is being generated as expected and so is `ConversionServiceAdapter`, and yet, `ConversionService` fails to convert from `Foo` to `FooDto`.

Am I missing something here? Is there some configuration I need to do after all? I feel like I exhausted the available documentation on this issue. Thanks in advance!

edit: It doesn't seem to be a problem with Spring. I've just tested it, and Converters that aren't generated are detected automatically.

**Comment by filiphr** [comment]
From what I can see you have `@Mapper` which means that the default component model is used, which means that the generated mapper is not a Spring bean. In order for things to work properly with spring your mappers need to be spring beans as well. i.e. you need to use `@Mapper(componentModel = "spring")`

**Comment by Chessray** [comment]
Hi,

On top of what @filiphr already pointed out, the project is missing the [central configuration](https://mapstruct.org/documentation/spring-extensions/reference/html/#mappersAsConvertersCustomNames) which allows e.g. specifying the package name for the generated Adapter class. Without this, the Adapter would be generated into the default package which you typically don't want inside a SpringBoot project, because the component scan will miss it.

**Comment by Chessray** [comment]
Thanks for the feedback. We'll consider it. :-)

On another note: If all you want to do is register Mappers as converters, you don't need the extensions project. This is only required for more advanced use cases.
