### ISSUE TITLE
No converter found capable of converting from type X to type Y

### ISSUE THREAD

**Issue by pojacks** [mapstruct/mapstruct-spring-extensions#46]
I've seen the previous issues in the subject, but event though I inject `ConversionService` to my code and use the `convert()` function, I get the error. I've couldn't manage to understand the solution suggested in [this comment](https://github.com/mapstruct/mapstruct-spring-extensions/issues/22#issuecomment-793679758), but anyway this is not ideal.

Any idea why this can happen? I'm really getting stuck because of this.

I also have another converter on the classpath, if that matters.

**Comment by pojacks** [comment]
Sidenote - when I look at the path of the generated code, I really do see `build/generated/sources/annotationProcessor/java/main/my.package/ConversionServiceAdapter.java`. But I can see the generated code of the conversion.

**Comment by Chessray** [comment]
There is most likely an issue with your project build setup. Can you share a minimal example?

**Comment by pojacks** [comment]
@Chessray turns out the problem what pretty embarrassing. I didn't declare the `mapstruct-processor` as `annotationProcessor` in the Gradle file.

But for future cases where people get this error I suggest to add the mapstruct regular dependencies to the documentation of the `mapstruct-spring-extensions` usage. e.g. here:
![mapstruct](https://user-images.githubusercontent.com/105706126/172887588-a64ffb19-dfa1-42ce-86d1-78973b8607b4.png)
