### ISSUE TITLE
Map lists

### ISSUE THREAD

**Issue by hypercube-software** [mapstruct/mapstruct-spring-extensions#65]
It seems that mapping lists is not really possible, the generated code is not able to understand the type of the list:

```
public List<MyTarget> mapListToList(final List<MySource> source) {
       return conversionService.convert(source,List.class)
}
```
I have also the same generated method 2 times if I have the conversion in the both directions. the compiler end up saying "name clash: mapListToList.... and mapListToList have the same type erasure"

For lists, another method should be used in the interface ConversionService (see this [stackoverflow](https://stackoverflow.com/a/23981806)):

`Object convert(Object source, TypeDescriptor sourceType, TypeDescriptor targetType)`

It would be nice if the documentation could say something about this

**Comment by Chessray** [comment]
This is a funny one. The linked solution using `TypeDescriptor`s relies on another Spring-internal mechanism.

Looking at this a bit closer: What is your actual use case? Are you trying to define a `Converter<List<A>, List<B>>`?

**Comment by hypercube-software** [comment]
indeed, I just want to convert a List<A> to a List<B>

**Comment by coding-guo** [comment]
I have the same problem,I want to achieve such a requirement，I defined two mapper
----------------------------------------
First:
`@Mapper(componentModel = "spring")
public interface AreaMapperStruct extends Converter<List<Area>, List<AreaSimpleOutDTO>> {
    @Override
    List<AreaSimpleOutDTO> convert(List<Area> areaList);
}`

The second：
`@Mapper(componentModel = "spring")
public interface PartTypeMapperStruct extends Converter<List<PartType>, List<PartTypeOut>> {
    @Override
    List<PartTypeOut> convert(List<PartType> partTypes);
}`
Compile Error：
`public class ConfigurationServiceAdapter {
  private final ConversionService conversionService;

  public ConfigurationServiceAdapter(
      @Qualifier("partTypeConversionService") @Lazy final ConversionService conversionService) {
    this.conversionService = conversionService;
  }

  public List<PartTypeOut> mapListToList(final List<PartType> source) {
    return conversionService.convert(source, List.class);
  }

  public DeviceBrand mapDeviceBrandOptDTOToDeviceBrand(final DeviceBrandOptDTO source) {
    return conversionService.convert(source, DeviceBrand.class);
  }

  public AlarmCode mapAlarmCodeOptDTOToAlarmCode(final AlarmCodeOptDTO source) {
    return conversionService.convert(source, AlarmCode.class);
  }

  public List<AreaSimpleOutDTO> mapListToList(final List<Area> source) {
    return conversionService.convert(source, List.class);
  }
}`

have two "mapListToList" method，how can i solve this problem

**Comment by Chessray** [comment]
Will have to look into this a bit. Until we can provide a full solution, the best thing I can suggest is not implementing the List Mapper as a Spring Converter and following standard MapStruct instead.

**Comment by coding-guo** [comment]
Thank you and look forward to a better solution！！



> Will have to look into this a bit. Until we can provide a full solution, the best thing I can suggest is not implementing the List Mapper as a Spring Converter and following standard MapStruct instead.

**Comment by Chessray** [comment]
Some notes:
- The method `TypeDescriptor.collection` explicitly states that it's only applicable to anything extending the `Collection` interface. We should be able to check that.
- Cater for nested Generics, e.g. `List<Set<Object>>`.
- If we do this, we want to do it right.
