### ISSUE TITLE
Support SpringBoot3

### ISSUE THREAD

**Issue by kronofogden-ulf-westermark** [mapstruct/mapstruct-spring-extensions#66]
Good extension, however according to https://github.com/mapstruct/mapstruct-spring-extensions/blob/main/gradle/libs.versions.toml 
this is build for SpingBoot 2.7 and should support SpringBoot 3 to avoid a lot of CVE-complaints and to support the latest 
released version of SpringBoot

**Comment by Chessray** [comment]
We support Spring Boot 3. The listed dependency is only used for example purposes. We cannot update this yet, as that would require updating the whole build to JDK 17. That would break compatibility with the core project.
