### ISSUE TITLE
how can i use "Inverse mappings" 

### ISSUE THREAD

**Issue by kevinmails** [mapstruct/mapstruct-spring-extensions#71]
My code like this:
`public interface CarMapper extends Converter<Car, CarDTO> {
    @Override
    @Mappings(
           @Mapping(source = "wheels",target = "carWheels")
    )
    CarDTO convert(Car source);
}`

how can i get a  Inversed method "Car convert(CarDTO source);"

**Comment by Chessray** [comment]
There's no built-in way to achieve this. Spring Converters work in only one direction. If you require a two-way mapping, you'll have to define a second Converter skeleton.
