### ISSUE TITLE
Problem of defining parent-child JPA mapping.

### ISSUE THREAD

**Issue by fajksk-dev** [mapstruct/mapstruct-spring-extensions#75]
In my current project I've started to use mapstruts together with mapstruct-spring-extension and when I've started to save jpa objects generated by convertes I've realized that dependent object in relations like one-to-many are not saved. Reason for that is that child object doesn't contain reference to it's parent. Solution for this issue is provided by mapstructs and described in one of examples. I've struggled to achieve same behavior in together with spring-extension, but without success.
Mappers interfaces needs to extend Converter interface from spring, where there is one argument method convert and in order to achieve effect from https://github.com/mapstruct/mapstruct-examples/tree/main/mapstruct-jpa-child-parent somehow we need to pass @Context param. Is there any way of solving this problem ?

**Comment by Chessray** [comment]
Spring's `Converter` interface is very opinionated in this regard and does not allow anything like MapStruct's `@Context`. I've struggled with this scenario in the past and opted not to follow the Spring Converter model with this kind of Mapper.

**Comment by fajksk-dev** [comment]
I see, but is there any other way of achieving same behavior in mapstruct-spring-extension ? If not I'll have to use directly basic mapstruct in few particular cases.

**Comment by Chessray** [comment]
One way I can imagine is defining a Wrapper class that contains both the original and the information you'd typically put into the context. But building a full hierarchy like that sounds too complex for most use cases.

Another way might be defining some type of dynamic lookup object that can be injected into the Mapper as well as the calling code. That idea obviously comes with its own cost and headache, so you'd have to decide for yourself whether it's worth it.

Spring really expects all information required for mapping in the source object. You might be better off using MapStruct core for these cases.
