### ISSUE TITLE
How to inject Spring CustomComponent in Mapper interface? 

### ISSUE THREAD

**Issue by albilu** [mapstruct/mapstruct-spring-extensions#84]
I am trying to achieve the following but not sure if this is what this extensions is meant for. I am a bit confused.

I will like to inject a custom service in the CarMapper interface extending the Spring Converter.

It seems injection is not possible with CarMapper interface but only with abstract classes.

Is it possible to achieve this while keeping the integration with the Spring ConversionService?

```java
@Mapper(componentModel = "spring")
public interface CarMapper extends Converter<Car, CarDto> {

    @Autowired
    private MyCustomService myCustomService;//This is not working

    @Mapping(target = "title", expression = "java(getLocaleTitle(car)))
    CarDto convert(Car car);
    

    default String getLocaleTitle(Car car) {
        return myCustomService.translate(car.getTitle());
    }
}
```

**Usage**:
```java
@Autowired
    private ConversionService conversionService;
...
    Car car = ...;
    CarDto carDto = conversionService.convert(car, CarDto.class);
```

**Comment by Chessray** [comment]
Why don't you make the Mapper an abstract class instead? By the way, this doesn't require the extension at all. As [the documentation](https://mapstruct.org/documentation/spring-extensions/reference/html/#mapperAsConverter) says:

> All this can be achieved already with MapStruct’s core functionality.

With or without the extension, nothing prevents you from writing

`public abstract class CarMapper implements Converter<Car, CarDto>`

**Comment by albilu** [comment]
@Chessray Thanks you it did work. Sorry for the confusion!
